### ISSUE TITLE
Upgrade code from python 2.7 to python 3

### ISSUE THREAD

**Issue by marktorng** [arungeorge101/myRobinhoodData#3]
Error

{'next': None, 'previous': None, 'results': []}
Traceback (most recent call last):
  File "rhDataAnalyzer.py", line 192, in <module>
    for key, stockList in stockDict.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

lines 191-201

      process the stocks in the dictionary and calculate P&L
for key, stockList in stockDict.iteritems():
    # variables to create the summary data
    totalBought = 0
    totalCost = 0
    avgCost = 0
    totalSold = 0
    totalSale = 0
    avgSale = 0
    profit = 0
    quantLeft = 0

excel file stockdata.xls is not created. 
excel file optionsdata.xls is created with only headers, no data.

**Comment by arungeorge101** [comment]
Since this was basically written for my own use, I didnt add much error logging.
I will add better error logging when I get some time so that its better for other people.

But in this case - do you have the options.json and orders.json file created in your folder?

**Comment by marktorng** [comment]
Both .json files were successfully created and contain data.

**Comment by arungeorge101** [comment]
Hi Mark,

This is happening because of python version mismatch. I wrote the code in 2.7 which uses dictionary.iteritems() and in Python3 this was replaced with dictionary.items(). I will update the code for python 3 as soon as I get some time.

But for now you can replace the below line:

"for key, stockList in stockDict.iteritems():"

with

"for key, stockList in stockDict.items():"

and run the code again. I will keep the issue open and close it once I upgrade the code to python 3.

**Comment by marktorng** [comment]
That worked! Thank you for your help
