### ISSUE TITLE
Stock excel sheet is not getting generated 

### ISSUE THREAD

**Issue by nitimish475** [arungeorge101/myRobinhoodData#6]
Traceback (most recent call last):
  File "rhDataAnalyzer.py", line 194, in <module>
    for key, stockList in stockDict.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

Also - were you able to look at the summary sheet, that feature would be awesome.

**Comment by arungeorge101** [comment]
The above issue happens since you are in python3 and the old code was in python2.7. This was updated by Kathryn and I have merged code to master. 

I have added a basic summary functionality. Please download the latest code and run it. 
Please follow instructions in read me and let me know if you see issues.

**Comment by nitimish475** [comment]
Thank you Arun and it is Awesome, working perfectly fine. 
Appreciate your help.
